### ISSUE TITLE
Matplotlib display inline

### ISSUE THREAD

**Issue by rwilleynyc** [learn-co-curriculum/dsc-0-01-18-looping-over-collections-lab#1]
plt.show() not working correctly because %matplotlib inline was not stated after importing matplotlib

**Comment by PeterBell** [comment]
Hi Raymond, thanks so much for catching that! Just resolved with https://github.com/learn-co-curriculum/dsc-1-01-20-looping-over-collections-lab/commit/770847bff77afcb43ee289977b613ad1d58f0c31
